# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35

install:
    - pip install -e .
    - pip install tox

script:
    - tox -e $TOX_ENV

notifications:
  email:
    on_success: never
    on_failure: change


